# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: simple-golang
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'
        cache: 'false'

    - name: Android
      run: GOOS=android GOARCH=arm64 go build -trimpath -v -x -o ./bin/golang/master-download ./src/golang/master-download.go

    - name: release
      uses: alexellis/upload-assets@0.4.1
        with:
          asset_paths: '["./bin/golang/master-download"]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
