name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Testing workflow'
        default: 'android-build'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23.5'
          go-version-file: './go.mod'
          cache: 'false'
          architecture: 'arm64'

      - name: 'android-build'
        run: GOOS=android GOARCH=arm64 go build -trimpath -v -x -ldflags=' -s' -o ./bin/golang/master-download ./src/golang/master-download.go

  greet:
    runs-on: ubuntu-22.04
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
