name: Manual workflow

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      name:
        description: 'Testing workflow'
        default: 'android-build'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.23.5'
          cache: 'false'
          
      - name: 'android-build'
        run: GOOS=android GOARCH=arm64 go build -trimpath -v -x -ldflags=' -s' -o ./bin/golang/master-download ./src/golang/master-download.go

      - name: release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: master-download
          path: ./bin/golang/master-download
          content-type: application/octet-stream
          repo-token: ${{ secrets.GITHUB_TOKEN }}
