# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Testing workflow'
        # Default value if no value is explicitly provided
        default: 'Android'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
jobs:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
    build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'

    - name: Android
      run: GOOS=android GOARCH=arm64 go build -trimpath -v -x -o ./bin/golang/master-download ./src/golang/master-download.go
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
